#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    iLeftArm1,      sensorPotentiometer)
#pragma config(Sensor, in2,    iLeftArm2,      sensorPotentiometer)
#pragma config(Sensor, in3,    iRightArm1,     sensorPotentiometer)
#pragma config(Sensor, in4,    iRightArm2,     sensorPotentiometer)
#pragma config(Sensor, in5,    iGyro,          sensorGyro)
#pragma config(Sensor, dgtl1,  iLeftEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  iRightEncoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  mogoSonar,      sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  mogoButton,     sensorTouch)
#pragma config(Sensor, I2C_1,  iLeftMogo,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  iRightMogo,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           arm_l1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm_r1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           arm_l2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           arm_r2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogo_l,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           mogo_r,        tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           chassis_l,     tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port9,           chassis_r,     tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port10,          roller,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int iLEFT1ARMREALPOS;
int iRIGHT1ARMREALPOS;
int iLEFT2ARMREALPOS;
int iRIGHT2ARMREALPOS;
bool bMogoType = true;


#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "aPROS.h"
#include "aMod_Vex_Comp_Control.c"
#include "aControllerLib.h"
#include "aGlobals.h"
#include "aMath.h"
#include "aMotor.h"

//#include "bRerunFunctions.h"

#include "cDrive.h"
#include "cMogo.h"
#include "cArm.h"

#include "bAutonFunctions.h"
#include "dAutonomous.h"
#include "dTasks.h"


void autonomous1 ( ) {			// stupid order of includes
	startTask(motorController);
	calibrateArm();
	arm1GoTo(775);
	startTask(MogoControl);
	tankWithoutTrueSpeed(50, 50);
	taskDelay(4000);
	tankWithoutTrueSpeed(0, 0);
	bDidAutonRun = true;

}

void
init( ) {
	strTeam = "Wiz"; // Set Robot Name to TWITCHY on the LCD
	bLCDAuton =
	bLCDUserControl = true;
}

void pre_auton(){
 bStopTasksBetweenModes = true;
}

task autonomous(){
  //autonomous1();
}


bool	writeFirstOrSecond;
int		writeArm1;
int		writeArm2;


task teleop(){

	calibrateArm();
	startTask(motorController);
	startTask(coneCountManager);

	if(bDidAutonRun == true){
		startTask(MogoControl);
	}
	else if(bDidAutonRun == false){
		arm1GoTo(775);
		startTask(MogoControl);
	}

	while(true){
   	tank(iRightDriveStick, iLeftDriveStick);

    if(bJ28U && bJ27U){
        stopTask(coneCountManager);
        stopTask(matchLoads);
        stopTask(statGoal);
        stopTask(fieldCones);
        startTask(dumbControl);
        while(bJ28U && bJ27U){
            taskDelay(20);
        }
    }




   	if(iConeStack > 12)
   		{ iConeStack = 12; }
		else if (iConeStack < 0)
			{ iConeStack = 12; }

		iLEFT1ARMREALPOS  = iGetArmL1();
		iRIGHT1ARMREALPOS = iGetArmR1();
		iLEFT2ARMREALPOS  = iGetArmL2();
		iRIGHT2ARMREALPOS = iGetArmR2();

		writeFirstOrSecond = (((iLEFT1ARMREALPOS + iRIGHT1ARMREALPOS)/2) > 700 ? false : true);
		writeArm1 = ((iLEFT1ARMREALPOS + iRIGHT1ARMREALPOS)/2);
		writeArm2 = ((iLEFT2ARMREALPOS + iRIGHT2ARMREALPOS)/2);
   	if(bPresetWriteBtn)
		{

      writeDebugStream("\n stackCone( %i, %i, %i );" , (writeArm1 + 250), writeArm2, writeFirstOrSecond);
			while(bPresetWriteBtn){ // Waits for the button to be released to start the task to prevent repeated task start
				delay( 20 ); //Don't hog the CPU!
			}
		}

		iConeOffset = ((iConeStack > 0) ? 140 * iConeStack : 125);

		if(!bIsJoystickAt(iJ2Ch2, 0)){
			iArmL1LockPos = ( (0 < iJ2Ch2) ? (iArmL1LockPos + 1) : (iArmL1LockPos - 1));
			iArmR1LockPos = ( (0 < iJ2Ch2) ? (iArmR1LockPos + 1) : (iArmR1LockPos - 1));
		}

		if(bManualArmLockSwitch){
    	while(bManualArmLockSwitch){ // Waits for the button to be released to start the task to prevent repeated task start
				delay( 20 ); //Don't hog the CPU!
			}
			if(bLockLeftArm1 == false){
				iArmL1LockPos = iGetArmL1();
			}
			if(bLockRightArm1 == false){
				iArmR1LockPos = iGetArmR1();
			}
			bLockLeftArm1 = !bLockLeftArm1;
			bLockRightArm1 = !bLockRightArm1;
		}

		if(bMogoType == false){
			if(bMogoUpBtn){ 			// if Button Up on Channel 6
				mogoLMotor = 127;
				mogoRMotor = 127;
			}
			else if(bMogoDwnBtn){ // if Button Down on Channel 6
				mogoLMotor = -127;
				mogoRMotor = -127;
			}
			else{						// If no butons are pressed
				mogoLMotor = 0;
				mogoRMotor = 0;
			}
		}

    taskDelay(20);
  }
}
